package com.p2pmessenger.gui;

import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.Set;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.UUID;
import com.p2pmessenger.client.P2PClientInterface;
import com.p2pmessenger.server.P2PServerInterface;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author ecl
 */
public class Solicitudes extends javax.swing.JDialog {

    /**
     * Creates new form Solicitudes
     */
    private P2PServerInterface s;
    private P2PClientInterface c;
    private String id;
    private UUID uuid;
    public Solicitudes(java.awt.Frame parent,P2PServerInterface servidor,P2PClientInterface cliente,String idpropio,UUID uuid) {
        super(parent, true);
        s=servidor;
        c=cliente;
        id=idpropio;
        uuid=uuid;
        initComponents();
        try {
            actualizarTabla(s.getSolicitudesPendientes(uuid, id));
            System.out.println(s.getSolicitudesPendientes(uuid, id));
        } catch (RemoteException e) {
            System.out.println("Error obteniendo las solicitudes pedientes.");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        aceptar = new javax.swing.JButton();
        rechazar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabla.setModel(new tablaSolicitudes());
        jScrollPane1.setViewportView(tabla);

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        rechazar.setText("Rechazar");
        rechazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechazarActionPerformed(evt);
            }
        });

        jLabel1.setText("Solicitudes:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(aceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(rechazar)
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rechazar)
                    .addComponent(aceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechazarActionPerformed
        // TODO add your handling code here:
        /*try{
        //s.rechazarSolicitud(this.id,this.c,tabla.getValueAt(tabla.getSelectedRow(), 0));
        } catch (RemoteException e) {
            System.out.println("Error rechazando solicitud")
        }*/
    }//GEN-LAST:event_rechazarActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        try {
            System.out.println("Id aceptador."+this.id);
            System.out.println("Aceptado"+(String)tabla.getValueAt(tabla.getSelectedRow(), 0));
            s.aceptarSolicitud(this.id,this.uuid,(String)tabla.getValueAt(tabla.getSelectedRow(), 0));
        } catch (RemoteException e) {
            System.out.println("Error aceptando solicitud");
        }
    }//GEN-LAST:event_aceptarActionPerformed

     public void actualizarTabla(ArrayList<String> solicitudes) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Solicitudes");
       
        for(Object s:solicitudes){
            modelo.addRow(new Object[]{s});
        }
        tabla.setModel((TableModel) modelo);
        if (modelo.getRowCount() > 0) {
            tabla.setRowSelectionInterval(0, 0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rechazar;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
