package com.p2pmessenger.gui;

import java.rmi.RemoteException;
import java.util.HashMap;
import java.util.Set;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import com.p2pmessenger.client.Client_Interface;
import com.p2pmessenger.server.P2PServerInterface;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ecl
 */
public class Vprincipal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    private P2PServerInterface s;
    private Client_Interface c;
    private String id;
    private HashMap<String,Client_Interface> amigos;
    public Vprincipal(P2PServerInterface servidor,Client_Interface cliente,String id) {
        initComponents();
        s=servidor;
        c=cliente;
        try {
            amigos=s.getAmigosOnline(cliente,id);
            System.out.println(amigos.keySet());
        } catch (RemoteException e) {
            System.out.println("Error obteniendo la lista de amigos.");
        }
        //Actualizo tabla
        actualizarTabla(amigos.keySet());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setModel(new tablausuarios());
        jScrollPane1.setViewportView(tabla);

        jMenu2.setText("Solicitudes");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Añadir amigo");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 381, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    public void actualizarTabla(Set conectados) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Amigos");
       
        for(Object s:conectados){
            modelo.addRow(new Object[]{s});
        }
        tabla.setModel((TableModel) modelo);
        if (modelo.getRowCount() > 0) {
            tabla.setRowSelectionInterval(0, 0);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
